### ISSUE TITLE
Can read any file via the delegates website

### ISSUE THREAD

**Issue by picatextra** [X-CASH-official/XCASH_DPOPS#10]
I was able to read all files on the system.
A malicious user could use this to access the delegate wallet.

Steps :

- Using Postman

- use URL   http:// _delegate_  `../../XCASH_DPOPS_INSTALL.log`

- put ` .html` somewhere in the request (User-Agent for example)

(curl and firefox don't send the `..`)

![image](https://user-images.githubusercontent.com/4353090/68713058-4989e680-059d-11ea-8600-27bd95ad7b6a.png)

The server should reject request with the string `..`

**Comment by zachhildreth** [comment]
Hi @picatextra 
I reviewed the above steps and was able to confirm that this does work in postman, but not in a browser.

## We are awarding the bug bounty for this bug to you!

### CVSS Score
### We have determined that the [CVSS score for this bug](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:N/CR:H/IR:H/AR:L/MAV:N/MAC:L/MPR:N/MUI:N/MS:C/MC:H/MI:H/MA:N&version=3.1) is a 10

So according to the [Bug Bounty official documentation](https://docs.xcash.foundation/contribute/bug-bounty-program) this bug qualifies for a award between $500.00 and $1000.00 USD

We have calculated the final amount in USD based on the following criteria


| Question                                     | Answer  |
| -------------------------------------------- | --------------------------- |
| How does the bug affect the block chain or DPOPS design                                      | It has nothign do with this  |
| Does this affect all users                                                         | NO, only ones that run either of the websites |
| What is the impact level to the users                                            | It is a high impact |
| Was there any modification to the code to create the bug  | NO |
| Did the user provide a full code fix                                | NO, but in this case it was not necessary  |
| Did the bug have to do with multi-threading                       | NO |
| Could the tester use a debugger, static analysis or both |static analysis, since the test has not started the block production process yet at the moment|
| Are we currently in Alpha, Beta or Live implementation of DPOPS |ALPHA|
 

## Based on the above the team has decided that the final awarded amount will be $700.00 USD

### Please post a X-CASH Wallet address in the comments, and we will send the payment, post the tx hash and then close the issue.

Thank you for helping out the DPOPS by finding this bug.

**Comment by picatextra** [comment]
Thanks !
 XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws

**Comment by plbgnt** [comment]
Bounty Paid ✅ 
--------------
Date: 14/11/2019
Amount (USD): $700
Amount (XCASH): 14880276.23 XCASH
Spot Price: 0.0000470421374862335 USD/XCASH
XCASH Address: XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws 
Tx Hash: e9f572afcf34a21b3bc921020c8c3e14126731d45ef3bfaae41f1837339fa00c 
Link: https://explorer.x-cash.org/Transaction?data=e9f572afcf34a21b3bc921020c8c3e14126731d45ef3bfaae41f1837339fa00c
