### ISSUE TITLE
Crash if a request has a body

### ISSUE THREAD

**Issue by picatextra** [X-CASH-official/XCASH_DPOPS#12]
I can make a delegate crash with a request having a body

curl http://127.0.0.1:18283/getdelegatesvoterslist?parameter1=aaa -d '{}'

**Comment by picatextra** [comment]
@zachhildreth , the last commit solve this crash,
But i can make an other crash if the request don't have `\r\n` 
 in` parse_json_data` function , it should check if str2!=null

`curl 127.0.0.1:18283 -d '{ "message_settings": "BLOCK_VERIFIERS_TO_BLOCK_VERIFIERS_DELEGATES_DATABASE_DOWNLOAD_FILE_UPDATE", "file": "0", "public_address":"", "previous_block_hash": "", "current_round_part": "1", "current_round_part_backup_node": "0", "data": "",}' -H 'Content-Type: application/json' -X GET`

**Comment by zachhildreth** [comment]
Thanks for re checking this after the provided fixes, I will take a look at it!

**Comment by zachhildreth** [comment]
Hi @picatextra 

### CVSS Score
### We have determined that the [CVSS score for this bug](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H/E:X/RL:X/RC:R/CR:X/IR:X/AR:H/MAV:L/MAC:L/MPR:N/MUI:N/MS:U/MC:X/MI:X/MA:H&version=3.1) is a 7.7

So according to the [Bug Bounty official documentation](https://docs.xcash.foundation/contribute/bug-bounty-program) this bug qualifies for a award between $250.00 and $500.00 USD

We have calculated the final amount in USD based on the following criteria


| Question                                     | Answer  |
| -------------------------------------------- | --------------------------- |
| How does the bug affect the block chain or DPOPS design                                      | It has nothing do with this  |
| Does this affect all users                                                         | affected all users |
| What is the impact level to the users                                            | It is a high impact |
| Was there any modification to the code to create the bug  | NO |
| Did the user provide a full code fix                                | NO  |
| Did the bug have to do with multi-threading                       | NO |
| Could the tester use a debugger, static analysis or both |static analysis, since the test has not started the block production process yet at the moment|
| Are we currently in Alpha, Beta or Live implementation of DPOPS |ALPHA|

Although it was noted that the tester was able to find an additional bug after checking the provided fix, and this did increase the price.
 

## Based on the above the team has decided that the final awarded amount will be $350.00 USD

### Please post a X-CASH Wallet address in the comments, and we will send the payment, post the tx hash and then close the issue.

Thank you for helping out the DPOPS by finding this bug.

**Comment by picatextra** [comment]
XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws

**Comment by plbgnt** [comment]
### **Bounty Paid** ✅ 
--------------
**Date:** 2019-03-12
**Amount (USD):** $350
**Amount (XCASH):** 11931202.06 XCASH
**Spot Price:** 0.0000293348480972966 USD/XCASH
**XCASH Address:** XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws 
**Tx Hash:** aa8c10c6d6caf0651442a70d4252a94ece4c524636740c85c83eb8f3f5abaa50 
**Link:** https://explorer.x-cash.org/Transaction?data=aa8c10c6d6caf0651442a70d4252a94ece4c524636740c85c83eb8f3f5abaa50
